#!/usr/bin/env node
/**
 * This is a service that has an express HTTP server exposing a subset of the rai_node
 * RPC protocol. It also connects to an MQTT server
 * for pub/sub operations and uses Redis and PostgreSQL for state management.
 */

const fs = require('fs')
const express = require('express')
const bodyParser = require('body-parser')
const mqtt = require('mqtt')
const mqttRegex = require('mqtt-regex')  // Used to parse out parameters from wildcard MQTT topics
const request = require('request')
const extend = require('extend')       // To merge objects
const winston = require('winston')     // Solid logging lib
const redis = require('redis')         // For maintaining session state
const { Pool } = require('pg')         // For proper database stuff
const neodoc = require('neodoc')       // For nice command line opts

// Parse out command line
const args = neodoc.run(`
Usage:
  canoed [--initialize] [--config=<path>]
  canoed -h | --help | --version
`, { optionsFirst: true, smartOptions: true })

// Default config that is extended (merged) with CONFIG_FILE
var CONFIG_FILE = 'canoed.conf'
if (args["--config"]) {
  CONFIG_FILE = args["--config"]
}

var config = {
  logging: {
    level: 'info'
  },
  debug: false,
  server: {
    port: 8080
  },
  rainode: {
    host: '[::1]',
    port: 7076
  },
  postgres: {
    user: 'canoe',
    host: 'localhost',
    database: 'canoe',
    password: 'secretpassword',
    port: 5432
  },
  redis: {
    host: 'localhost',
    port: 6379
  },
  mqtt: {
    url: 'tcp://localhost',
    options: {
      clientId: 'canoed',
      username: 'canoed',
      password: '1234'
    },
    subacl: '[{"pattern": "#"}]',
    pubacl: '[{"pattern": "#"}]',
    block: {
      opts: {
        qos: 2,
        retain: false
      }
    }
  }
}

// MQTT Client
var mqttClient = null

// Postgres pool client
var pool = null

// Redis Client
var redisClient = null

// An Express server to handle REST calls, either from Canoe or from rai_node callback
var restServer = null

// Patterns for topics
var walletMqttRegex = mqttRegex('wallet/+id/accounts').exec
var broadcastMqttRegex = mqttRegex('broadcast/+account').exec

// Flag to indicate we have already subscribed to topics
var subscribed = false

// Read configuration
function configure () {
  // Read config file if exists
  if (fs.existsSync(CONFIG_FILE)) {
    try {
      var fileConfig = JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'))
      extend(true, config, fileConfig)
    } catch (e) {
      winston.error('Failed to parse config file: ' + CONFIG_FILE + e.message)
      process.exit(1)
    }
  }
  winston.level = config.logging.level
}

// Connect Postgres
function connectPostgres () {
  pool = new Pool(config.postgres)
  winston.info('Connected to Postgres')
}

// Initialize database for VerneMQ auth
// We also need:  CREATE EXTENSION pgcrypto;
// But that needs superuser privilege to do.
async function initializeDb () {
  var sql = `
  DROP TABLE IF EXISTS public.vmq_auth_acl;
  CREATE TABLE vmq_auth_acl
  (
    mountpoint character varying(10) NOT NULL,
    client_id character varying(128) NOT NULL,
    username character varying(128) NOT NULL,
    password character varying(128),
    publish_acl json,
    subscribe_acl json,
    CONSTRAINT vmq_auth_acl_primary_key PRIMARY KEY (mountpoint, client_id, username)
  );`
  const client = await pool.connect()
  try {
    await client.query(sql)
  } catch (e) {
    winston.error('Error initializing db: ' + e)
  } finally {
    client.release()
  }
  await createAccount({
    wallet: config.mqtt.options.username, // This maps to clientId
    token: config.mqtt.options.username,
    tokenPass: config.mqtt.options.password,
    pubacl: '[{"pattern":"#"}]',
    subacl: '[{"pattern":"#"}]'
  })
}

// Connect Redis
function connectRedis () {
  winston.info('Connecting to Redis ...')
  redisClient = redis.createClient(config.redis.port, config.redis.host, {no_ready_check: true})
  /*redisClient.auth('password', function (err) {
    if (err) throw err
  })*/
  redisClient.on('connect', function () {
    winston.info('Connected to Redis')
  })
}

// Connect to MQTT
function connectMQTT () {
  mqttClient = mqtt.connect(config.mqtt.url, config.mqtt.options)
  mqttClient.on('connect', function () {
    winston.info('Connected to MQTT server')
    subscribe()
  })

  // Where all subscribed messages come in
  mqttClient.on('message', function (topic, message) {
    switch (topic) {
      case 'canoecontrol':
        return handleControl(message)
    }
    var params = walletMqttRegex(topic)
    if (params) {
      return handleWalletAccounts(params.id, message)
    }
    var params = broadcastMqttRegex(topic)
    if (params) {
      return handleBroadcastBlock(params.account, message)
    }
    winston.error('No handler for topic %s', topic)
  })
}

function publishBlock (topic, payload) {
  winston.debug('Publish: ' + topic + ' block: ' + JSON.stringify(payload))
  mqttClient.publish(topic, JSON.stringify(payload), config.mqtt.block.opts)
}

// Subscribe to control
function subscribe () {
  if (!subscribed) {
    mqttClient.subscribe('canoecontrol')
    mqttClient.subscribe('wallet/+/accounts')
    mqttClient.subscribe('broadcast/+') // account number
    winston.debug('Subscribed to selected topics')
    // /+/ for wildcards
    subscribed = true
  }
}

function handleWalletAccounts (walletId, message) {
  var accounts = JSON.parse(message)
  setWalletForAccounts(accounts, walletId, (err, res) => {
    if (err) {
      winston.error('Error setting wallet for accounts: ' + err)
    } else {
      winston.debug('Set wallet ' + walletId +' for accounts ' + message)
    }
  })
}

function handleBroadcastBlock (account, message) {
  winston.debug('Broadcast for account ' + account + ' block ' + message)
}

function handleControl (message) {
  var control = JSON.parse(message)
  winston.debug('PARSED CONTROL: ', control)
  // TODO handle control commands
}

// Start the REST server
function startRESTServer () {
  restServer = express()
  restServer.use(bodyParser.json({
    inflate: true,
    limit: '100kb',
    type: function (req) { return true } // Callbacks don't come with a media type so we always presume JSON in body
  }))

  // The RPC functions we offer Canoe
  restServer.post('/rpc', function (req, res) {
    winston.debug('GET URL', req.url)
    // winston.debug('HEADERS', req.headers)
    // winston.debug('QUERY', req.query)
    // winston.debug('BODY', req.body)
    // winston.debug('CONTENT', req.content)

    var spec = req.body
    var action = req.body.action
    switch (action) {
      case 'create_server_account':
        return createAccount(spec).then((r) => { res.json(r) })
      case 'canoe_server_status':
        return res.json(canoeServerStatus(spec))
      case 'quota_full':
        return res.json(quotaFull(spec))
      case 'update_server_map':
        return res.json(updateServerMap(spec))
      case 'process':
        return processBlock(spec).then((r) => { res.json(r) })
      case 'available_supply':
        return availableSupply(spec).then((r) => { res.json(r) })
      case 'accounts_pending':
        return accountsPending(spec).then((r) => { res.json(r) })
      case 'account_history':
        return accountHistory(spec).then((r) => { res.json(r) })
      case 'blocks_info':
        return blocksInfo(spec).then((r) => { res.json(r) })
      case 'work_generate':
        return workGenerate(spec).then((r) => { res.json(r) })
      default:
        return res.json({error: 'unknown action'})
    }
  })

  // The rai_node callback entry point
  restServer.post('/callback', function (req, res) {
    // winston.debug('POST URL ' + req.url)
    // winston.debug('HEADERS ' + JSON.stringify(req.headers))
    // winston.debug('QUERY ' + JSON.stringify(req.query))
    // winston.debug('POSTBODY ' + JSON.stringify(req.body))
    // winston.debug('IP', req.connection.remoteAddress)
    handleRaiCallback(req.body)
    // We can return immediately
    res.json({})
  })

  restServer.listen(config.server.port)
  winston.info('Http server started on port ' + config.server.port)
}

function quotaFull (spec) {
  return {full: false}
}

function updateServerMap (spec) {
  // for acc in accounts:
  //  redis.setk("xrb:" & acc.getStr, walletId)
  // return %*{"status": "ok"}
}

function canoeServerStatus (spec) {
  // Called if calls fail to get a message to show
  if (fs.existsSync('canoeServerStatus.json')) {
    return JSON.parse(fs.readFileSync('canoeServerStatus.json'))
  }
  return {status: 'ok'}
}

function availableSupply (spec) {
  return callRainode(spec)
}

function accountsPending (spec) {
  return callRainode(spec)
}

function accountHistory (spec) {
  return callRainode(spec)
}

function blocksInfo (spec) {
  return callRainode(spec)
}

function workGenerate (spec) {
  return callRainode(spec)
}

function processBlock (spec) {
  return callRainode(spec)
}

// Create an account given a walletId, token and a tokenPass
async function createAccount (spec) {
  var values = [spec.wallet, spec.token, spec.tokenPass,
    spec.pubacl || config.mqtt.pubacl,
    spec.subacl || config.mqtt.subacl]
  var sql = `WITH x AS (
    SELECT
        ''::text AS mountpoint,
           $1::text AS client_id,
           $2::text AS username,
           $3::text AS password,
           gen_salt('bf')::text AS salt,
           $4::json AS publish_acl,
           $5::json AS subscribe_acl
    ) 
INSERT INTO vmq_auth_acl (mountpoint, client_id, username, password, publish_acl, subscribe_acl)
    SELECT 
        x.mountpoint,
        x.client_id,
        x.username,
        crypt(x.password, x.salt),
        publish_acl,
        subscribe_acl
    FROM x ON CONFLICT DO NOTHING;`
  const client = await pool.connect()
  try {
    winston.debug('Creating account: ' + JSON.stringify(values))
    await client.query(sql, values)
    winston.debug('Created account: ' + JSON.stringify(values))
    return {status: 'ok'}
  } catch (e) {
    winston.error('Error creating account: ' + e)
    return {error: '' + e}
  } finally {
    client.release()
  }
}

function getWalletForAccount (account, cb) {
  winston.debug('Get wallet for account: ' + account)
  redisClient.get('accounts:' + account, cb)
}

function setWalletForAccounts (accounts, walletId, cb) {
  var pairs = []
  for (let acc of accounts) {
    pairs.push('accounts:' + acc)
    pairs.push(walletId)
  }
  redisClient.set(pairs, cb)
}

function handleRaiCallback (blk) {
  // winston.debug('Block: ' + JSON.stringify(blk))
  var blk2 = JSON.parse(blk.block)
  winston.debug('Acc: ' + blk.account + ' Block: ' + blk2.type + ' amount: ' + blk.amount)

  // Now we can pick out type of block
  var blkType = blk2.type
  var account = blk.account
  // var amount = blk.amount

  // Switch on block type
  switch (blkType) {
    case 'open':
      getWalletForAccount(account, function (err, wallet) {
        if (err) throw err
        if (wallet) {
          winston.debug('Wallet found: ' + wallet.toString())
          publishBlock('wallet/' + wallet.toString() + '/block/open', blk)
        }
      })
      return
    case 'send':
      account = blk2.destination
      getWalletForAccount(account, function (err, wallet) {
        if (err) throw err
        if (wallet) {
          publishBlock('wallet/' + wallet.toString() + '/block/send', blk)
        }
      })
      return
    case 'receive':
      getWalletForAccount(account, function (err, wallet) {
        if (err) throw err
        if (wallet) {
          publishBlock('wallet/' + wallet.toString() + '/block/receive', blk)
        }
      })
      return
    case 'change':
      winston.debug('A change block ignored')
      return
  }
  winston.error('Unknown block type: ' + blkType)
}

// Make POST call to rai_node
function callRainode (payload) {
  return new Promise(function (resolve, reject) {
    request.post({
      url: 'http://' + config.rainode.host + ':' + config.rainode.port,
      headers: {'content-type': 'application/json'},
      body: JSON.stringify(payload),
      timeout: 60000,
      callback: function (err, response, body) {
        if (err) {
          winston.debug('ERROR', err)
          reject(err)
        } else {
          var answer = JSON.parse(body)
          winston.debug('ANSWER: ', JSON.stringify(answer))
          resolve(answer)
        }
      }
    })
  })
}

// Want to notify before shutting down
function handleAppExit (options, err) {
  if (err) {
    winston.error(err.stack)
  }
  if (options.cleanup) {
    winston.info('Cleaning up...')
    if (mqttClient) {
      mqttClient.end(true)
    }
  }
  if (options.exit) {
    winston.info('Calling exit...')
    process.exit()
  }
}

function configureSignals () {
  // Handle the different ways an application can shutdown
  process.on('exit', handleAppExit.bind(null, {
    cleanup: true
  }))
  process.on('SIGINT', handleAppExit.bind(null, {
    exit: true
  }))
  process.on('uncaughtException', handleAppExit.bind(null, {
    exit: true
  }))
}


// Let's start doing something
configure()
configureSignals()
connectPostgres()

if (args["--initialize"]) {
  winston.debug('Initializing database ...')
  initializeDb().then(
    () => {
      winston.debug('Initialization done.')
      process.exit(0)
    },
    err => {
      winston.debug('Initialization failed: ' + err)
      process.exit(0)
    }
  )
} else {
  connectRedis()
  connectMQTT()
  startRESTServer()
}
